# Generated by Django 2.2.16 on 2021-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
