# Generated by Django 2.2.16 on 2021-08-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
