# Generated by Django 2.2.16 on 2021-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_genretitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviews.GenreTitle', to='reviews.Genres'),
        ),
    ]
