# Generated by Django 2.2.6 on 2021-08-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20210819_0904'),
    ]

    operations = [
    ]
